### PR TITLE
Make private variables

### PR DESCRIPTION
**Pull request by Abhishek01039**

### CODE REVIEW

**Comment by Abhishek01039** [comment]
@theindianinnovation 
can you please review the PR?
Thanks

**Comment by Abhishek01039** [comment]
Simulator Screen Shot - iPhone 12 - 2021-01-03 at 15 57 23
Simulator Screen Shot - iPhone 12 - 2021-01-03 at 15 57 27

**Review by theindianinnovation — APPROVED** [review]
Made it more better and efficient

**Comment by Abhishek01039** [comment]
it's my pleasure @theindianinnovation

**Pull request merged**
